apiVersion: v1
kind: Service
metadata:
  name: kanscan-ingest
  annotations:
    maesh.containo.us/traffic-type: http
spec:
  ports:
  - port: 80
    targetPort: 9090
  selector:
    app: kanscan-ingest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanscan-ingest
spec:
  selector:
    matchLabels:
      app: kanscan-ingest
  replicas: 2
  template:
    metadata:
      labels:
        app: kanscan-ingest
    spec:
      containers:
      - name: kanscan-ingest
        image: "charlesdburton/kanscan-ingest:latest"
        ports:
        - containerPort: 7777
        imagePullPolicy: Always
        env:
        - name: INGEST_HOST
          value: "nats-cluster"
        - name: INGEST_PORT
          value: "4222"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-redirect-kanscan-ingest
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`kanscan-ingest.home.rsmachiner.com`)
      kind: Rule
      services:
        - name: kanscan-ingest
          port: 80
      middlewares:
        - name: redirect
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroutetls-kanscan-ingest
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`kanscan-ingest.home.rsmachiner.com`)
    kind: Rule
    services:
    - name: kanscan-ingest
      port: 80
  tls:
    certResolver: default